version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - ./backend:/app/backend
      - ./main.js:/app/main.js
    ports:
      - "8080:8080"